movies/details/urls.py
from django.contrib import admin
from django.urls import path
from details import views
app_name="details"

urlpatterns = [
    # path('',views.home,name="home"),
    path('',views.homeview.as_view(),name="home"),

    # path('add/',views.add,name="add"),
    path('add/',views.add.as_view(),name="add"),

    # path('details/<int:n>/',views.details,name="details"),
    path('details/<int:pk>/',views.details.as_view(),name="details"),

    # path('delete/<int:n>/',views.delete,name="delete"),
    path('delete/<int:pk>/',views.delete.as_view(),name="delete"),

    # path('update/<int:n>/',views.update,name="update"),
    path('update/<int:pk>/',views.update.as_view(),name="update"),


]

movies/movies/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name="details"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('details.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/details/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=30)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='movies',null=True,blank=True)

    def __str__(self):
        return self.name

movies/details/forms.py
from django import forms
from details.models import Movie


class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

movies/details/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from details.models import Movie
from .forms import movieform
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView

# def home(request):
#     m=Movie.objects.all
#     return render(request,'home.html',{'m':m})

class homeview(ListView):
    model=Movie
    template_name="home.html"
    context_object_name='m'


# def add(request):
#     if(request.method=="POST"):
#         n=request.POST['n']
#         y=request.POST['y']
#         d=request.POST['d']
#         i=request.FILES['i']
#         m=Movie.objects.create(name=n,year=y,desc=d,image=i)
#         m.save()
#         return home(request)
#     return render(request,'add.html')

class add(CreateView):
    model=Movie
    template_name="add1.html"
    fields=['name','desc','year','image']
    success_url=reverse_lazy('details:home')


# def details(request,n):
#     m=Movie.objects.get(id=n)
#     return render(request,'details.html',{'m':m})

class details(DetailView):
    model=Movie
    template_name="details.html"
    context_object_name='m'

# def delete(request,n):
#     m=Movie.objects.get(id=n)
#     m.delete()
#     return home(request)

class delete(DeleteView):
    model=Movie
    template_name="delete.html"
    success_url=reverse_lazy('details:home')

# def update(request,n):
#     m=Movie.objects.get(id=n)
#     if(request.method=="POST"):
#         form=movieform(request.POST,request.FILES,instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=movieform(instance=m)
#     return render(request,'add1.html',{'form':form})

class update(UpdateView):
    model = Movie
    template_name = "add1.html"
    fields = ['name', 'desc', 'year', 'image']
    success_url = reverse_lazy('details:home')




# Create your views here.

movies/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add movies
{% endblock %}
{% block content %}
<h1>Add Movies</h1>
<h4> This page is used to add Movies </h4>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" class="form-control"  name="n" placeholder="Enter Movie Name">
  </div>
      <div class="mb-3">
    <label class="form-label">Year</label>
    <input type="number" class="form-control"  name="y" placeholder="Enter Movie Year">
  </div>
      <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control"  name="d" placeholder="Enter Movie Description">
  </div>
      <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="file" class="form-control"  name="i" placeholder="Add Movie Image">
  </div>
      <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

movies/templates/add1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add movies
{% endblock %}
{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {%csrf_token%}

  {{form}}
    <input type="submit">
</form>
{% endblock %}

movies/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

      <link rel="stylesheet" href="{% static 'css/mov.css' %}">
</head>
<body style="background-color:#73a5f5;">
<nav class="navbar navbar-light" style="background-color:#e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand">Movie Store</a>
    <form class="d-flex">
        <a class="btn btn-outline-dark btn-success" href="{% url 'details:add' %}">Add Movies</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

movies/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add movies
{% endblock %}
{% block content %}
<form method="POST"  enctype="multipart/form-data">
    {%csrf_token%}

  {{form}}
    <div style="text-align:center;">
    <h5>Are you sure to delete this file</h5>
    <input type="submit">
        </div>
</form>
{% endblock %}

movies/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add movies
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <img src="{{m.image.url }}" height="500px;">
         </div>
    <div class="col-md-6">
        <h1>{{m.name}}</h1>
        <h4>{{m.year}}</h4>
        <h6>{{m.desc}}</h6>
        <a class="btn btn-secondary" href="{% url 'details:update' m.id %}">Update</a>
        <a class="btn btn-secondary" href="{% url 'details:delete' m.id %}">Delete</a>

        </div>


</div>

{% endblock %}

movies/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container-fluid">
     <div class="row">
         {% for i in m %}
         <div class="col-sm-3 mt-3">

          <div class="card" style="width:20rem;height:500px">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." height="300px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>

      <p class="card-text">{{i.year}}</p>
    <a href="{% url 'details:details' i.id %}" class="btn btn-primary">Details.....</a>
  </div>
</div>
         </div>


         {% endfor %}



     </div>
 </div>
{% endblock %}